version: "3"
services:
  backend:
    build: .
    ports:
      - 8081:80
    env_file:
      - backend.env
  db:
    image: postgres:14.2
    env_file:
      - db.env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8082:8080
    restart: always

volumes:
  postgres:
