name: Build and Publish Docker Image
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python manage.py test
        env:
          SECRET_KEY: this-is-a-test-secret-key
          ALLOWED_HOSTS: "*"
          DATABASE_URL: "sqlite://:memory:"
          CORS_ORIGIN_WHITELIST: "http://localhost"
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_PASSWORD: admin
          CSRF_TRUSTED_ORIGINS: "http://localhost"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: zkhan93/oms-backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "latest,${{ steps.date.outputs.date }}"
