name: Create a tag
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: phish108/autotag-action@1.1.37
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"
